### ISSUE TITLE
目前也是按照教程配置完成以后，as没有Start a new Flutter project

### ISSUE THREAD

**Issue by limuen** [flutterchina/website#59]
去as下边下载相对应的flutter和dart的包。
flutter doctor后出现[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3) ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
按照报错信息执行flutter doctor --android-licenses 报错
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by limuen** [comment]
已解决
